### PR TITLE
Consider adding code coverage

### PR DESCRIPTION
**Pull request by pascalduez**
Just trying out.

Provides some interesting insights on how the codebase is tested.
Travis reports directly to https://coveralls.io
Coveralls add a comment on PRs to report coverage changes. See SassDoc/sass-convert#8

What do you think, useful or not ?

### CODE REVIEW

**Comment by pascalduez** [comment]
screen shot 2015-01-25 at 18 18 28

**Comment by HugoGiraudel** [comment]
Okay on core repository only.

**Comment by valeriangalliat** [comment]
We maybe need to refactore CLI tests in makefile to be executed through Node so we can test CLI coverage?

**Comment by pascalduez** [comment]
> We maybe need to refactore CLI tests in makefile to be executed through Node so we can test CLI coverage?

That's what I thought, but does not seem to really influence the result ?

There is a minor issue:
Coveralls fetch files from Github to display them, but `dist` is not git tracked. 
https://coveralls.io/r/SassDoc/sassdoc
Actually we don't really need coveralls, except if we want a nice badge and make the results public.
Istanbul provides html reports: `make view-cover`.

**Comment by valeriangalliat** [comment]
`view-cover` should depend on `cover` (empty result if `make cover` was not manually executed before).

**Comment by HugoGiraudel** [comment]
When is this going to be released?

**Comment by pascalduez** [comment]
Depends whether we get a consensus from @SassDoc/owners ?

I personally like it, it's a good way to motivates us to write more tests, and also discover hidden issues.
The coveralls integration is not mandatory.

**Comment by valeriangalliat** [comment]
:+1:

**Comment by FWeinb** [comment]
:+1:

**Comment by pascalduez** [comment]
Most recent status.
Would be interesting to add tests for Environment.

screen shot 2015-01-26 at 20 57 04

**Comment by HugoGiraudel** [comment]
Shall we open an issue about increasing test coverage? 80% is pretty neat, but I'd like us to bump 90-95% if it's doable.

**Comment by pascalduez** [comment]
We won't reach 100% anyway, due to the ES(6|2015) transpilation, there's some snippets from 6to5 that aren't called, and would make no sense for us to test them. 
But for sure, we can improve things.

**Pull request merged**
