### PR TITLE
Prevent duplicate entries in requirements

### PR DESCRIPTION
**Pull request by reneroth**
Fixes issue #530 :)

### CODE REVIEW

**Comment by castastrophe** [comment]
This would be very helpful for my team - is there any way I can help to get this PR merged and a release rolled with it?

**Comment by pascalduez** [comment]
@castastrophe Hello,
yes, we would like a few unit tests added to assert the behavior and prevent later regressions.

**Comment by castastrophe** [comment]
- [ ] @castastrophe to add unit tests

[_adding this as a reminder to myself to pick this up_]

**Comment by reneroth** [comment]
👀

**Comment by castastrophe** [comment]
@reneroth Sorry about this - I committed to doing this and promptly started a new job and have been doing some intense onboarding. I'll see if I can get back into this at some point in the near future but also open to anyone else picking it up if they like.

**Comment by reneroth** [comment]
> @reneroth Sorry about this - I committed to doing this and promptly started a new job and have been doing some intense onboarding. I'll see if I can get back into this at some point in the near future but also open to anyone else picking it up if they like.

Haha no worries friend! I just stumbled across this when reviewing my open pull requests, completely forgot about it :D

**Comment by reneroth** [comment]
Closing this PR for selfish reasons because I want an "inbox zero" kind of feeling for my PR list.  
Code is functional if anyone still needs it.

**Pull request closed without merging**
