### PR TITLE
[RFR] Switch to ESlint

### PR DESCRIPTION
**Pull request by pascalduez**
- Waiting for babel/babel-eslint#31
- `space-before-function-parentheses` or `space-before-function-paren` does not seem to work
- A few fixes left

### CODE REVIEW

**Comment by valeriangalliat** [comment]
Awesome work!

Feels **really** good to remove all these ignore comments.

**Comment by pascalduez** [comment]
Plus it's driving out much more possible issues than JShint.

**Comment by HugoGiraudel** [comment]
Terrific. Only the tests to fix before merging. :)

**Comment by pascalduez** [comment]
Something to discuss:
```
src/cli.js
  45:6  error  Don't use process.exit(); throw an error instead  no-process-exit
  48:4  error  Don't use process.exit(); throw an error instead  no-process-exit
```
http://eslint.org/docs/rules/no-process-exit.html

I guess we can mute this rule.

**Comment by HugoGiraudel** [comment]
Any reason we do exit instead of throwing an error?

**Comment by valeriangalliat** [comment]
> Any reason we do exit instead of throwing an error?

To control the exit code.

+1 to mute the rule, it's not meaningful in the CLI, it's only relevant inside the library code (and we don't exit from the library).

**Comment by pascalduez** [comment]
```
src/annotation/annotations/require.js
  190:39  error  isAnnotatedByHand is already declared in the upper scope  no-shadow
```

https://github.com/SassDoc/sassdoc/blob/master/src/annotation/annotations/require.js#L182-L201

I wondering how is able to work ?

**Comment by valeriangalliat** [comment]
`searchForMatches` is calling the `isAnnotatedByHand` function passed as a parameter. It don't uses the upper scope declared function (though the calling code is actually passing it this very function, see `searchForMatches` calls).

**Comment by pascalduez** [comment]
Yeah, I removed my comment, just realized the `isAnnotatedByHand.bind(...)`
Renaming the parameter into `isAnnotatedByHandProxy`

**Comment by pascalduez** [comment]
So this is now Ready for review :-)

We are using all of [ESlint default rules](https://github.com/eslint/eslint/blob/master/conf/eslint.json), overriding just the few ones we don't agree with.
There's also a couple of style rules added.
I personally like this approach.

Another option is not to use any base rules with `--reset` and set all the rules our self.

**Comment by valeriangalliat** [comment]
I like it as is, okay to merge. :+1:

**Comment by pascalduez** [comment]
What about moving to adding a space between function declaration name and params.
Which brings us closer to [standard](https://github.com/feross/standard)

```js
function whatever (foo, bar) { ... } 
```

**Comment by valeriangalliat** [comment]
I'm all for following standard. I'm also okay with semistandard which is basically like standard but with semicolons (and thus will be more friendly with our codebase).

**Pull request merged**
