### PR TITLE
Add a debug option

### LINKED ISSUE #311: Consider adding a debug option
After seeing issues like #309 #310 and obviously other ones in the past, we could benefit from adding a new `-d --debug` options. 
This would not produce the final documentation but output useful information on the current environment. Either to `stdout` or in a `sassdoc-debug.log`.

- [x] SassDoc version
- [x] Node.js version
- [x] npm version
- [x] platform
- [x] CLI location (either global or local)
- [x] If CLI command run and options
- [x] is a plugin used (Grunt, Gulp, ...)
- [x] source path
- [x] destination path
- [x] CWD (maybe not useful for plugins?)
- [x] environment (implies config)
- [x] data

### PR DESCRIPTION
**Pull request by valeriangalliat**
* Closes #311
* Documentation: SassDoc/sassdoc.github.io#83

### CODE REVIEW

**Comment by pascalduez** [comment]
No review ?

**Comment by valeriangalliat** [comment]
We discussed this on Slack, see between 10:10 PM and 10:18 PM. Sorry to not have pinged you directly, if you wanna comment/ammend something, there's still room for this. :)

**Comment by pascalduez** [comment]
```
bin/sassdoc src -v --debug
```

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/local/Cellar/node/0.10.35_1/lib/node_modules/npm/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [...]/sassdoc/dist/sassdoc.js:327:14
    at [...]/sassdoc/dist/logger.js:70:20
    at Array.map (native)
    at [...]/sassdoc/dist/logger.js:68:53
    at chalkHack ([...]/sassdoc/dist/logger.js:88:3)
    at Logger.debug ([...]/sassdoc/dist/logger.js:67:7)
```

**Comment by valeriangalliat** [comment]
Interesting. I'm trying to get the npm version by searching the global npm module's `package.json`. It seems to not work everywhere… what do you advice to get global npm version? Relying on `PATH` and exec `npm --version`?

**Comment by pascalduez** [comment]
`require('npm').version` ?

**Comment by valeriangalliat** [comment]
Can't require global module. :/

**Comment by valeriangalliat** [comment]
Added a try/catch around in 133901985505e345965961f13aace7c7b0f2f13c, at least it won't crash the whole process.

**Pull request merged**
