### PR TITLE
Remove date from logger

### PR DESCRIPTION
**Pull request by pascalduez**
So `[18:26:48]` instead of superfluous `[2015-01-22 18:26:48]` 

Thoughts ?

### CODE REVIEW

**Comment by valeriangalliat** [comment]
The date was not needed indeed, neither is the time IMO.

**Comment by pascalduez** [comment]
> The date was not needed indeed, neither is the time IMO.

Time kind of make sense in a debug scenario, where one could merely check execution time... ?
But usually SassDoc performs in less than a second.

**Comment by pascalduez** [comment]
Maybe the normal (non debug) verbose mode should rather looks like:
```
[18:45:09] SassDoc task started
> Item "global-test" refers to "mixin-global-test" from type "mixin" but this item doesn't exist.
> Item "global-test" refers to "variable-global-test" from type "variable" but this item doesn't exist.
> Item "global-test" refers to "placeholder-global-test" from type "placeholder" but this item doesn't exist.
> Folder "./test/data" successfully parsed.
> Folder "sassdoc" successfully refreshed.
> Theme "default" successfully rendered.
> Process over. Everything okay!
[18:45:09] SassDoc task ended
``

**Comment by HugoGiraudel** [comment]
> Maybe the normal (non debug) verbose mode should rather looks like something in this vein ?

Looks nice.

**Comment by valeriangalliat** [comment]
> where one could merely check execution time

```sh
time sassdoc ...
```

**Comment by pascalduez** [comment]
So shall we go for the fancier formatting ? Or just keep it as is ?

```
SassDoc task started
★ Item "global-test" refers to "mixin-global-test" from type "mixin" but this item doesn't exist.
★ Item "global-test" refers to "variable-global-test" from type "variable" but this item doesn't exist.
★ Item "global-test" refers to "placeholder-global-test" from type "placeholder" but this item doesn't exist.
★ Folder "./test/data" successfully parsed.
★ Folder "sassdoc" successfully refreshed.
★ Theme "default" successfully rendered.
★ Process over. Everything okay!
SassDoc task ended in 200ms
```

**Comment by HugoGiraudel** [comment]
Could we have an octopus icon? :x

**Comment by pascalduez** [comment]
Might most likely be an unicode thing for it :-)

**Comment by HugoGiraudel** [comment]
Boom: http://www.fileformat.info/info/unicode/char/1f419/index.htm. &#128025;

**Comment by pascalduez** [comment]
Current status:
screen shot 2015-01-23 at 23 08 28

Still room for improvements.

**Comment by FWeinb** [comment]
I like it ✔

**Comment by HugoGiraudel** [comment]
:+1:

**Comment by valeriangalliat** [comment]
Looks good!

**Comment by pascalduez** [comment]
screen shot 2015-01-24 at 11 20 23

**Comment by valeriangalliat** [comment]
Errors have a red `»` too?

**Comment by pascalduez** [comment]
Those are just 'log' messages, I kept the [WARNING] and [ERROR] ones we already had.
Should we streamline all messages ?

**Comment by FWeinb** [comment]
Making it red on an error and yellow on a warning sound awesome

**Comment by valeriangalliat** [comment]
> Should we streamline all messages ?

I think so, but I don't know how. It's nice to differenciate heads-up from success with yellow/green but if we add this scheme for warning messages, they'd be yellow too…

Though "but this item doesn't exist" messages are kinda warnings to me.

**Comment by valeriangalliat** [comment]
I think we need to change the logger semantics (and function names):

| function | color |
| ----- | ------ |
| log (same as info) | default |
| success | green |
| warning | yellow |
| error | red |

**Comment by pascalduez** [comment]
Looks good. So I would also put the whole line colored for warning and error. 
Should we keep the [WARNING] and [ERROR] prepends ?
```
» [WARNING] You'd better watch out bro, something's broke.
```
```
» [ERROR] You're screwed anyway.
```

**Comment by valeriangalliat** [comment]
Visually, with colors, we don't need `[WARNING]` and `[ERROR]`, though it's really helpful when logs are saved to text files to search through them. it's the only way on non-colored terminals to differenciate informational messages from warnings and errors.

An alternative would be to replace the `»` with `I` `W` or `E` for respectively info, warning, error (in the corresponding color).

I don't think the whole line needs to be colored, only the `»` or "semantic leter" is enough.

**Comment by FWeinb** [comment]
I would include `[WARNING]` and `[ERROR]` and only color the chevron.

**Comment by pascalduez** [comment]
Okay for only having the prepended thing colored.

Although I like the `I` `W` or `E` I don't think it's straightforward enough for end users ?

**Comment by pascalduez** [comment]
> I would include [WARNING] and [ERROR] and only color the chevron.

:+1:  let's try

**Comment by valeriangalliat** [comment]
I don't know, I recall seeing this in unit test suites. Having the `[]` is okay too.

**Comment by FWeinb** [comment]
Let's look at the output of popular unit test frameworks

**Comment by pascalduez** [comment]
> I don't know, I recall seeing this in unit test suites. Having the [] is okay too.

What I meant is it's maybe a bit too nerdy :-) We have devsigner™ between SassDoc users.

**Comment by pascalduez** [comment]
screen shot 2015-01-24 at 12 21 27

screen shot 2015-01-24 at 12 23 53
*Stacktrace truncated from screenshot*

**Comment by FWeinb** [comment]
This looks awesome!

**Comment by valeriangalliat** [comment]
Perfect!

**Comment by pascalduez** [comment]
And the logger code has been considerably lightened/cleaned.

Also now that annotations use `warn` instead of `log`, the warnings appears in the tests. 
But I guess it even better, warnings should be considered, not ignored.

**Comment by pascalduez** [comment]
Mr @HugoGiraudel the last word maybe ?

**Comment by HugoGiraudel** [comment]
You guys rock. LGTM.

**Comment by pascalduez** [comment]
Thanks team for the great and constructive feedback !

**Comment by HugoGiraudel** [comment]
Tried it today, looks gorgeous. Love it.

**Comment by pascalduez** [comment]
And its now fully [tested / testable](https://github.com/SassDoc/sassdoc/blob/develop/test/src/logger.test.js).

**Comment by pascalduez** [comment]
@coveralls U drunk?

**Pull request merged**
