### PR TITLE
Full stream ahead

### PR DESCRIPTION
**Pull request by pascalduez**
Work in progress.

Centralize reviews and discussions.

Refs #287 

Important thing to note, the API usage is slightly modified:
```js
/**
 * All in one documentize function.
 */
var sassdoc = require('sassdoc');

var sd = sassdoc('src', { verbose: true });
sd.documentize().then(function () {
  console.log('yeah!');
});


/**
 * Stream pipelines.
 */
var vfs = require('vinyl-fs');
var sassdoc = require('sassdoc');

var sd = sassdoc({ verbose: true });
vfs.src('./src/**/*.scss')
  .pipe(sd.stream());


/**
 * Gulp integration (example).
 */
var gulp = require('gulp');
var sass = require('gulp-sass');
let converter = require('sass-convert');
var sassdoc = require('sassdoc');

gulp.task('styles', function () {
  var sd = sassdoc({ verbose: true });
  var docs = sd.stream();

  return gulp.src('./src/**/*.scss')
    .pipe(converter({ from: 'sass', to: 'scss' }))
    .pipe(docs)
    .pipe(sass())
    .pipe(gulp.dest('./dist'));
});
```

### CODE REVIEW

**Comment by FWeinb** [comment]
The stream usage looks awesome but this:
```js
  var ds = sassdoc({ verbose: true });
  var docs = sd.stream();
```
isn't that good. 

Can't we just always return a `stream` (maybe an enhanced one).

**Comment by FWeinb** [comment]
Summary of the discussion on Slack

This should be how it is used with gulp
```js
/**
 * Gulp integration (example).
 */
var gulp = require('gulp');
var sass = require('gulp-sass');
let converter = require('sass-convert');
var sassdoc = require('sassdoc').stream;
 
gulp.task('styles', function () {
  return gulp.src('./src/**/*.scss')
    .pipe(converter({ from: 'sass', to: 'scss' }))
    .pipe(sassdoc({ verbose: true }))
    .pipe(sass())
    .pipe(gulp.dest('./dist'));
});
```

And the general node api should look like:
```js
var sassdoc = require('sassdoc').promise;

sassdoc('src', { verbose: true }).then(function () {
  console.log('yeah!');
});
```

So I think that `console.log(require('sassdoc'));` should yield something like this:
```js
{
  'stream' : [Function], // A function that will bootstrap sassdoc and return a stream
  'promise' : [Function], // A function that will bottstrap sassdoc and return a promise
  'documentize' : [Function], // Legacy support ??? 
  
  // Advanced usage  
  'Parser' : [Function], // Parser constructor,
  'Environment' : [Function], // Environment constructor
  'Logger' : [Function] // Logger constructor
  
 'errors' : [] // errors 
}
```

**Comment by pascalduez** [comment]
Another idea would be to return depending on parameters. 
If `src` is passed, returns a Promise and run the full documentize stuff. 
If no `src` then returns the stream and run the parse stuff.


###### Note 1
The current way to require SassDoc (`develop`)  is:
```js
var sassdoc = require('sassdoc').default;
```
So a little refactor was desired here anyway.

###### Note 2
If we go either way, we loose the "instances" ability. Being able to document several projects in one place. But that quite an edge case I would say. And you can always require several times ?
```js
var sassdoc = require('sassdoc');

var projectOne = sassdoc('path/to/one', { verbose: true });
projectOne.documentize().then(function () {
  console.log('yeah!');
});

var projectTwo = sassdoc('path/to/two', { verbose: true });
projectTwo.documentize().then(function () {
  console.log('yeah again!');
});
``` 

@HugoGiraudel @valeriangalliat shim in !

**Comment by valeriangalliat** [comment]
> If we go either way, we loose the "instances" ability. Being able to document several projects in one place.

I don't get it. We don't loose the ability to document several projets if we have no mutable state at the module level (and I don't see where one would be needed… maybe the `error` array I see on your example above but I don't know what it's used for… really looks like global state though).

I'm all for exposing directly `stream` and `promise` functions, but I'm also okay with exporting a default function which will return a stream or a propise depending on the passed arguments.

So in fact `require('sassdoc')` could expose something like this:

```js
modue.exports = function sassdoc() {};
sassdoc.Parser = Parser;
sassdoc.Environment = Environment;
sassdoc.Logger = Logger;
```

**Comment by pascalduez** [comment]
Whoops, late night... --> chime in

**Comment by HugoGiraudel** [comment]
> @HugoGiraudel @valeriangalliat shim in !

You know I do not give my opinion anymore about technical choices. I am not good enough with JavaScript to emit a valuable advice. I trust you guys.

**Comment by pascalduez** [comment]
So @SassDoc/owners last call for review.

The API as been reworked as discussed above.
```js
var sassdoc = require('sassdoc');

/**
 * documentize
 * @return {Promise}
 */
sassdoc('./src', { verbose: true })
  .then(() => {
    console.log('yeah!');
  });

/**
 * stream
 * @return {Stream}
 */
vfs.src('./src/**/*.scss')
  .pipe(sassdoc({ verbose: true }))
  .pipe(whatever())
  .on('data', () => {});
```

Will open a new PR regarding stdin support.

**Comment by FWeinb** [comment]
This looks clean!  :+1: :fireworks:

**Pull request merged**
