### PR TITLE
Add a `debug` option

### LINKED ISSUE #406: --debug does not work with Gulp
In a Gulp setup, `debug: true` does not print anything.

```javascript
gulp.task('sassdoc', function () {
  return gulp
    .src('./**/*.scss')
    .pipe(sassdoc({
      dest: './views/sassdoc',
      config: './.sassdocrc', 
      debug: true,
      verbose: true
    }))
    .resume();
});
```

### PR DESCRIPTION
**Pull request by valeriangalliat**
Closes #406.

Documentation PR: SassDoc/sassdoc.github.io#119

### CODE REVIEW

**Comment by pascalduez** [comment]
:+1:

**Comment by valeriangalliat** [comment]
Well the PR is targeted on `develop`, and `develop` is meant to be the future 2.2 I guess, so I'll just merge into `develop`, without releasing anything.

**Comment by pascalduez** [comment]
Yup.

**Pull request merged**
